server:
  port: 1111
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

spring:
  profiles:
    active: dev
  application:
    name: cloud-eureka
    mainclass: com.eureka.EurekaApplication
