spring:
  profiles:
    active: native
  application:
    name: micro-config-server
  cloud:
    client:
      ipAddress: ${ipAddress}
    config:
      server:
        native:
          search-locations: file:E:\\my-project\\demo-config\\micro-record,file:E:\\my-project\\demo-config\\micro-busiconf
#        git:
#          uri:
#          username:
#          password:
#          search-paths: /micro-record,/micro-busiconf
    stream:
      bindings:
        springCloudBusOutput:
          destination: springCloudBus
      kafka:
        binder:
          brokers: ${kafka-brokers}
          zk-nodes: ${zk-nodes}
          configuration:
            auto:
              offset:                #可以设置原生kafka属性，比如设置新的消费组从最新的offset开始消费
                reset: latest
server:
  port: 7111

eureka:
  instance:
    lease-renewal-interval-in-seconds: 15
    lease-expiration-duration-in-seconds: 45
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

management:
  security:
    enabled: false
